### PR TITLE
vignere chipers with namespace

### PR DESCRIPTION
**Pull request by khairanabila**

### CODE REVIEW

**Comment by slowy07** [comment]
> request merge @slowy07 ,tested on clang, and [repl](https://repl.it) blush
good excelent, but why using namespace ?

**Comment by khairanabila** [comment]
> > request merge @slowy07 ,tested on clang, and [repl](https://repl.it) blush
> > good excelent, but why using namespace ?

im use this to prevent name collisions that can occur especially when your code base includes multiple libraries.
for the example
```cpp
namespace ContosoData
{
    class ObjectManager
    {
    public:
        void DoSomething() {}
    };
    void Func(ObjectManager) {}
}
```
more be efficient on base memmory allocation :blush:

**Review by slowy07 — APPROVED** [review]
LGTM and comments to!

**Comment by slowy07** [comment]
@all-contributors please add @ctrlbzul5  for infrastructure, tests and code

**Pull request merged**
